# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ro4nI9YXI7MdMjgPDOHw-9ODZFuFLfyJ
"""

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("1.jpg")
cv2_imshow(rasm1) # Changed rasm to rasm1

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY) # Changed rasm to rasm1
cv2_imshow(oqqora)

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("2.jpg")
cv2_imshow(rasm1) # Changed rasm to rasm1

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY) # Changed rasm to rasm1
cv2_imshow(oqqora)

!pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("3.jpg")
cv2_imshow(rasm1) # Changed rasm to rasm1

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY) # Changed rasm to rasm1
cv2_imshow(oqqora)